import { promises as fs } from "node:fs";
import path from "node:path";
import { getContextPaths } from "./templates.js";

export type InitResult = {
  created: string[];
  skipped: string[];
};

type IntegrationFileSpec = {
  relativePath: string;
  content: string;
};

const CONTEXT_FILES: Array<{ path: (paths: ReturnType<typeof getContextPaths>) => string; content: string }> = [
  {
    path: (paths) => paths.memoryPath,
    content: "# Memory\n\n- Update after meaningful project changes.\n- Keep concise, reusable context for future tasks.\n"
  },
  {
    path: (paths) => paths.workflowsPath,
    content: "# Workflows\n\n- Repeatable task playbooks (build, test, release, deploy).\n- Keep commands short and copy-paste ready.\n"
  },
  {
    path: (paths) => paths.decisionsPath,
    content: "# Decisions\n\n- Record important technical/product decisions and rationale.\n- Include date and impact.\n"
  },
  {
    path: (paths) => paths.preferencesPath,
    content: "# Preferences\n\n- Team coding preferences, style, and constraints.\n- Preserve these in all generated changes.\n"
  },
  {
    path: (paths) => paths.configPath,
    content:
      '{\n' +
      '  "memory": {\n' +
      '    "enabled": true,\n' +
      '    "maxItems": 8,\n' +
      '    "maxTokens": 1200,\n' +
      '    "includeTypes": ["rule", "preference", "decision", "project_state", "fact", "warning", "style"],\n' +
      '    "excludeTypes": [],\n' +
      '    "strictRedaction": true\n' +
      '  }\n' +
      '}\n'
  },
  {
    path: (paths) => paths.aiContextPath,
    content: "# AI Context\n\nGenerated by awesome-context-engine sync.\n"
  },
  {
    path: (paths) => paths.projectMapPath,
    content: "# Project Map\n\nGenerated by awesome-context-engine index.\n"
  },
  {
    path: (paths) => paths.minimalContextPath,
    content: "# Minimal Context\n\nGenerated by awesome-context-engine sync.\n"
  }
];

const INTEGRATION_FILES: IntegrationFileSpec[] = [
  {
    relativePath: ".github/copilot-instructions.md",
    content:
      "# Copilot Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md for repo structure.\n- Use .awesome-context/workflows.md and .awesome-context/skills/ for repeatable tasks.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- After completing tasks, suggest updates to .awesome-context/memory.md.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "AGENTS.md",
    content:
      "# Agent Rules\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md for repo structure.\n- Use .awesome-context/workflows.md and .awesome-context/skills/ for repeatable tasks.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- After completing tasks, suggest updates to .awesome-context/memory.md.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "CLAUDE.md",
    content:
      "# Claude Project Rules\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md for repo structure.\n- Use .awesome-context/workflows.md and .awesome-context/skills/ for repeatable tasks.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- After completing tasks, suggest updates to .awesome-context/memory.md.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: ".clinerules",
    content:
      "Read .awesome-context/ai-context.md first.\nUse .awesome-context/project-map.md and .awesome-context/workflows.md.\nPreserve preferences from .awesome-context/preferences.md.\nAfter each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\nSuggest updates to .awesome-context/memory.md after meaningful changes.\nNever store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: ".continue/context.md",
    content:
      "# Continue Context\n\n- Read `.awesome-context/ai-context.md` first.\n- Use `.awesome-context/project-map.md` and `.awesome-context/workflows.md` for structure and repeatable task flow.\n- Preserve preferences from `.awesome-context/preferences.md`.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to `.awesome-context/memory.md` after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  }
];

const REQUIRED_INTEGRATION_MARKERS = [
  ".awesome-context/ai-context.md",
  ".awesome-context/project-map.md",
  ".awesome-context/workflows.md",
  ".awesome-context/preferences.md",
  ".awesome-context/memory.md",
  "never store secrets"
];

const INTEGRATION_BLOCK_START_MD = "<!-- awesome-context-engine:integration:start -->";
const INTEGRATION_BLOCK_END_MD = "<!-- awesome-context-engine:integration:end -->";

function buildIntegrationAppendBlock(spec: IntegrationFileSpec): string {
  const isMarkdown = spec.relativePath.endsWith(".md");
  if (isMarkdown) {
    return [
      INTEGRATION_BLOCK_START_MD,
      "## awesome-context-engine Integration",
      "",
      "- Read .awesome-context/ai-context.md first.",
      "- Use .awesome-context/project-map.md and .awesome-context/workflows.md.",
      "- Preserve preferences from .awesome-context/preferences.md.",
      "- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.",
      "- Suggest updates to .awesome-context/memory.md after meaningful changes.",
      "- Never store secrets, tokens, credentials, or private keys in memory files.",
      INTEGRATION_BLOCK_END_MD,
      ""
    ].join("\n");
  }

  return [
    "",
    "# awesome-context-engine integration",
    "Read .awesome-context/ai-context.md first.",
    "Use .awesome-context/project-map.md and .awesome-context/workflows.md.",
    "Preserve preferences from .awesome-context/preferences.md.",
    "After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.",
    "Suggest updates to .awesome-context/memory.md after meaningful changes.",
    "Never store secrets, tokens, credentials, or private keys in memory files.",
    ""
  ].join("\n");
}

function upsertMarkdownIntegrationBlock(existing: string, block: string, placeAtTop: boolean): string {
  const startIndex = existing.indexOf(INTEGRATION_BLOCK_START_MD);
  const endIndex = existing.indexOf(INTEGRATION_BLOCK_END_MD);

  if (startIndex >= 0 && endIndex > startIndex) {
    const afterEnd = endIndex + INTEGRATION_BLOCK_END_MD.length;
    return `${existing.slice(0, startIndex).trimEnd()}\n\n${block}\n${existing.slice(afterEnd).trimStart()}`.trimEnd() + "\n";
  }

  const trimmed = existing.trim();
  if (!trimmed) {
    return `${block}\n`;
  }

  if (placeAtTop) {
    return `${block}\n${trimmed}\n`;
  }

  return `${trimmed}\n\n${block}\n`;
}

async function ensureIntegrationFile(filePath: string, spec: IntegrationFileSpec): Promise<"created" | "updated" | "unchanged"> {
  try {
    const existing = await fs.readFile(filePath, "utf8");
    const isMarkdown = spec.relativePath.endsWith(".md");
    if (!isMarkdown) {
      const lower = existing.toLowerCase();
      const hasAllMarkers = REQUIRED_INTEGRATION_MARKERS.every((marker) => lower.includes(marker.toLowerCase()));
      if (hasAllMarkers) {
        return "unchanged";
      }
    }

    const appendBlock = buildIntegrationAppendBlock(spec);
    const placeAtTop = spec.relativePath === ".github/copilot-instructions.md";
    const next = isMarkdown
      ? upsertMarkdownIntegrationBlock(existing, appendBlock, placeAtTop)
      : `${existing.trimEnd()}\n\n${appendBlock}`;

    if (next.trim() === existing.trim()) {
      return "unchanged";
    }

    await fs.writeFile(filePath, next, "utf8");
    return "updated";
  } catch (error) {
    const errorCode = (error as NodeJS.ErrnoException).code;
    if (errorCode !== "ENOENT") {
      throw error;
    }

    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, spec.content, "utf8");
    return "created";
  }
}

async function writeIfMissing(filePath: string, content: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return false;
  } catch {
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, content, "utf8");
    return true;
  }
}

export async function initProject(rootDir: string): Promise<InitResult> {
  const contextPaths = getContextPaths(rootDir);
  const created: string[] = [];
  const skipped: string[] = [];

  await fs.mkdir(contextPaths.contextDir, { recursive: true });
  await fs.mkdir(contextPaths.skillsDir, { recursive: true });
  await fs.mkdir(contextPaths.memoryDir, { recursive: true });

  const memoryStoreFiles: Array<{ filePath: string; content: string }> = [
    { filePath: contextPaths.memoryItemsPath, content: "[]\n" },
    { filePath: contextPaths.memorySummariesPath, content: "[]\n" },
    { filePath: contextPaths.memoryIndexPath, content: '{\n  "byTag": {},\n  "byType": {},\n  "updatedAt": null\n}\n' }
  ];

  for (const entry of memoryStoreFiles) {
    const wasCreated = await writeIfMissing(entry.filePath, entry.content);
    const relativePath = path.relative(rootDir, entry.filePath) || entry.filePath;
    if (wasCreated) {
      created.push(relativePath);
    } else {
      skipped.push(relativePath);
    }
  }

  for (const entry of CONTEXT_FILES) {
    const filePath = entry.path(contextPaths);
    const wasCreated = await writeIfMissing(filePath, entry.content);
    const relativePath = path.relative(rootDir, filePath) || filePath;
    if (wasCreated) {
      created.push(relativePath);
    } else {
      skipped.push(relativePath);
    }
  }

  for (const entry of INTEGRATION_FILES) {
    const filePath = path.join(rootDir, entry.relativePath);
    const status = await ensureIntegrationFile(filePath, entry);
    if (status === "created" || status === "updated") {
      created.push(entry.relativePath);
    } else {
      skipped.push(entry.relativePath);
    }
  }

  return { created, skipped };
}
