import { promises as fs } from "node:fs";
import path from "node:path";
import { getContextPaths } from "./templates.js";

export type InitResult = {
  created: string[];
  skipped: string[];
};

type IntegrationFileSpec = {
  relativePath: string;
  content: string;
};

const CONTEXT_FILES: Array<{ path: (paths: ReturnType<typeof getContextPaths>) => string; content: string }> = [
  {
    path: (paths) => paths.memoryPath,
    content: "# Memory\n\n- Update after meaningful project changes.\n- Keep concise, reusable context for future tasks.\n"
  },
  {
    path: (paths) => paths.workflowsPath,
    content: "# Workflows\n\n- Repeatable task playbooks (build, test, release, deploy).\n- Keep commands short and copy-paste ready.\n\n## Agent Command Triggers\n\nRules for AI agents: fire these commands based on what is happening in the conversation, not on a schedule.\n\n| Situation | Command to run |\n|---|---|\n| User asks to work on a specific file | `ace context:pack <file>` — load context before starting |\n| You (agent) finish making file changes | `ace sync` — rebuild ai-context.md |\n| User says \"remember this\", \"note that\", \"keep this in mind\" | `ace genesis capture --note \"<lesson>\"` |\n| User asks \"what did we decide\", \"do you remember\", \"what was the pattern\" | `ace genesis recall \"<topic>\"` |\n| User asks what files depend on X or impact of a change | `ace context:impact <file>` |\n| User asks to summarize or explain a file for context | `ace context:explain <file>` |\n| User adds a persistent preference or rule | `ace memory add \"<content>\"` |\n| User asks what you remember about the project | `ace memory list` |\n| Session starts fresh and no context loaded yet | `ace context:pack <entry-file>` then read the output |\n\n## Rules\n- NEVER run `ace auto` — it is a continuous file watcher that consumes RAM. It is not for agent use.\n- Run `ace sync` after every set of file changes, not before.\n- Run `ace context:pack` at the START of working on a file, not after.\n- `ace genesis capture` should store lessons, patterns, and decisions — not raw file content.\n- Do not run commands speculatively. Only fire when the situation matches the trigger above.\n"
  },
  {
    path: (paths) => paths.decisionsPath,
    content: "# Decisions\n\n- Record important technical/product decisions and rationale.\n- Include date and impact.\n"
  },
  {
    path: (paths) => paths.preferencesPath,
    content: "# Preferences\n\n- Team coding preferences, style, and constraints.\n- Preserve these in all generated changes.\n"
  },
  {
    path: (paths) => paths.configPath,
    content:
      '{\n' +
      '  "autoScanOnInit": true,\n' +
      '  "memory": {\n' +
      '    "enabled": true,\n' +
      '    "maxItems": 8,\n' +
      '    "maxTokens": 1200,\n' +
      '    "includeTypes": ["rule", "preference", "decision", "project_state", "fact", "warning", "style"],\n' +
      '    "excludeTypes": [],\n' +
      '    "strictRedaction": true\n' +
        '  },\n' +
        '  "cache": {\n' +
        '    "enabled": true,\n' +
        '    "incremental": true\n' +
        '  },\n' +
        '  "context": {\n' +
        '    "defaultTokenBudget": 4000,\n' +
        '    "maxRelatedFiles": 8\n' +
        '  },\n' +
        '  "learning": {\n' +
        '    "enabled": true,\n' +
        '    "captureByDefault": false,\n' +
        '    "requireApprovalForProfile": true,\n' +
        '    "autoApproveSafeProfile": true,\n' +
        '    "maxExperienceFiles": 500,\n' +
        '    "skillSuggestionThreshold": 3,\n' +
        '    "recallLimit": 8\n' +
      '  },\n' +
      '  "skills": {\n' +
      '    "enabled": false\n' +
      '  }\n' +
      '}\n'
  },
  {
    path: (paths) => paths.aiContextPath,
    content: "# AI Context\n\nGenerated by awesome-context-engine sync.\n"
  },
  {
    path: (paths) => paths.projectMapPath,
    content: "# Project Map\n\nGenerated by awesome-context-engine index.\n"
  },
  {
    path: (paths) => paths.minimalContextPath,
    content: "# Minimal Context\n\nGenerated by awesome-context-engine sync.\n"
  },
  {
    path: (paths) => path.join(paths.contextDir, "memory-index.json"),
    content: "{}\n"
  },
  {
    path: (paths) => path.join(paths.contextDir, "profile.json"),
    content:
      '{\n' +
      '  "version": 1,\n' +
      '  "preferences": {\n' +
      '    "naming": [],\n' +
      '    "coding": [],\n' +
      '    "docs": []\n' +
      '  },\n' +
      '  "projects": {},\n' +
      '  "sources": {}\n' +
      '}\n'
  },
  {
    path: (paths) => path.join(paths.contextDir, "skill-suggestions.json"),
    content: "[]\n"
  }
];

const INTEGRATION_FILES: IntegrationFileSpec[] = [
  {
    relativePath: ".github/copilot-instructions.md",
    content:
      "# Copilot Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md for repo structure.\n- Use .awesome-context/workflows.md and .awesome-context/skills/ for repeatable tasks.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- After completing tasks, suggest updates to .awesome-context/memory.md.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "AGENTS.md",
    content:
      "# Agent Rules\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md for repo structure.\n- Use .awesome-context/workflows.md and .awesome-context/skills/ for repeatable tasks.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- After completing tasks, suggest updates to .awesome-context/memory.md.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "CLAUDE.md",
    content:
      "# Claude Project Rules\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md for repo structure.\n- Use .awesome-context/workflows.md and .awesome-context/skills/ for repeatable tasks.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- After completing tasks, suggest updates to .awesome-context/memory.md.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: ".clinerules",
    content:
      "Read .awesome-context/ai-context.md first.\nUse .awesome-context/project-map.md and .awesome-context/workflows.md.\nPreserve preferences from .awesome-context/preferences.md.\nAfter each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\nSuggest updates to .awesome-context/memory.md after meaningful changes.\nNever store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: ".continue/context.md",
    content:
      "# Continue Context\n\n- Read `.awesome-context/ai-context.md` first.\n- Use `.awesome-context/project-map.md` and `.awesome-context/workflows.md` for structure and repeatable task flow.\n- Preserve preferences from `.awesome-context/preferences.md`.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to `.awesome-context/memory.md` after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "GEMINI.md",
    content:
      "# Gemini CLI Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "AIDER.md",
    content:
      "# Aider Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "OPENCODE.md",
    content:
      "# OpenCode Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "OPENCLAW.md",
    content:
      "# OpenClaw Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "FACTORY_DROID.md",
    content:
      "# Factory Droid Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "TRAE.md",
    content:
      "# Trae Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "HERMES.md",
    content:
      "# Hermes Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "KIRO.md",
    content:
      "# Kiro Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: "GOOGLE-ANTIGRAVITY.md",
    content:
      "# Google Antigravity Instructions\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  },
  {
    relativePath: ".cursor/rules/awesome-context.mdc",
    content:
      "---\ndescription: awesome-context-engine context and memory rules\nglobs:\nalwaysApply: true\n---\n# awesome-context-engine Rules\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After completing tasks that changed files, run `ace sync` to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n\n## When to fire ACE commands\n\n| Situation | Command |\n|---|---|\n| Starting work on a file | `ace context:pack <file>` |\n| Finished making changes | `ace sync` |\n| User says remember/note/keep in mind | `ace genesis capture --note \"<lesson>\"` |\n| User asks what was decided / do you remember | `ace genesis recall \"<topic>\"` |\n| User asks impact of changing a file | `ace context:impact <file>` |\n| User adds a rule or preference | `ace memory add \"<content>\"` |\n| Fresh session, no context loaded | `ace context:pack <entry-file>` |\n\n**Never run `ace auto`** — it is a RAM-heavy background watcher, not for agent use.\n"
  },
  {
    relativePath: ".cursorrules",
    content:
      "# awesome-context-engine Rules (Cursor legacy)\n\n- Read .awesome-context/ai-context.md first.\n- Use .awesome-context/project-map.md and .awesome-context/workflows.md.\n- Preserve preferences from .awesome-context/preferences.md.\n- After completing tasks that changed files, run awesome-context-engine sync to refresh context.\n- Suggest updates to .awesome-context/memory.md after meaningful changes.\n- Never store secrets, tokens, credentials, or private keys in memory files.\n"
  }
];

const REQUIRED_INTEGRATION_MARKERS = [
  ".awesome-context/ai-context.md",
  ".awesome-context/project-map.md",
  ".awesome-context/workflows.md",
  ".awesome-context/preferences.md",
  ".awesome-context/memory.md",
  "never store secrets"
];

const INTEGRATION_BLOCK_START_MD = "<!-- awesome-context-engine:integration:start -->";
const INTEGRATION_BLOCK_END_MD = "<!-- awesome-context-engine:integration:end -->";

function isMarkdownFile(relativePath: string): boolean {
  return relativePath.endsWith(".md") || relativePath.endsWith(".mdc");
}

function buildIntegrationAppendBlock(spec: IntegrationFileSpec): string {
  const isMarkdown = isMarkdownFile(spec.relativePath);
  if (isMarkdown) {
    return [
      INTEGRATION_BLOCK_START_MD,
      "## awesome-context-engine Integration",
      "",
      "- Read .awesome-context/ai-context.md first.",
      "- Use .awesome-context/project-map.md and .awesome-context/workflows.md.",
      "- Preserve preferences from .awesome-context/preferences.md.",
      "- After each completed prompt result that changed files, run `ace sync` to refresh context.",
      "- Suggest updates to .awesome-context/memory.md after meaningful changes.",
      "- Never store secrets, tokens, credentials, or private keys in memory files.",
      "",
      "### When to fire ACE commands",
      "",
      "| Situation | Command |",
      "|---|---|",
      "| Starting work on a file | `ace context:pack <file>` |",
      "| Finished making changes | `ace sync` |",
      "| User says remember/note/keep in mind | `ace genesis capture --note \"<lesson>\"` |",
      "| User asks what was decided / do you remember | `ace genesis recall \"<topic>\"` |",
      "| User asks impact of changing a file | `ace context:impact <file>` |",
      "| User adds a rule or preference | `ace memory add \"<content>\"` |",
      "| Fresh session, no context loaded | `ace context:pack <entry-file>` |",
      "",
      "**Never run `ace auto`** — it is a RAM-heavy background watcher, not for agent use.",
      INTEGRATION_BLOCK_END_MD,
      ""
    ].join("\n");
  }

  return [
    "",
    "# awesome-context-engine integration",
    "Read .awesome-context/ai-context.md first.",
    "Use .awesome-context/project-map.md and .awesome-context/workflows.md.",
    "Preserve preferences from .awesome-context/preferences.md.",
    "After each completed prompt result that changed files, run awesome-context-engine sync to refresh context.",
    "Suggest updates to .awesome-context/memory.md after meaningful changes.",
    "Never store secrets, tokens, credentials, or private keys in memory files.",
    ""
  ].join("\n");
}

function upsertMarkdownIntegrationBlock(existing: string, block: string, placeAtTop: boolean): string {
  const startIndex = existing.indexOf(INTEGRATION_BLOCK_START_MD);
  const endIndex = existing.indexOf(INTEGRATION_BLOCK_END_MD);

  if (startIndex >= 0 && endIndex > startIndex) {
    const afterEnd = endIndex + INTEGRATION_BLOCK_END_MD.length;
    return `${existing.slice(0, startIndex).trimEnd()}\n\n${block}\n${existing.slice(afterEnd).trimStart()}`.trimEnd() + "\n";
  }

  const trimmed = existing.trim();
  if (!trimmed) {
    return `${block}\n`;
  }

  if (placeAtTop) {
    return `${block}\n${trimmed}\n`;
  }

  return `${trimmed}\n\n${block}\n`;
}

async function ensureIntegrationFile(filePath: string, spec: IntegrationFileSpec): Promise<"created" | "updated" | "unchanged"> {
  try {
    const existing = await fs.readFile(filePath, "utf8");
    const isMarkdown = isMarkdownFile(spec.relativePath);
    if (!isMarkdown) {
      const lower = existing.toLowerCase();
      const hasAllMarkers = REQUIRED_INTEGRATION_MARKERS.every((marker) => lower.includes(marker.toLowerCase()));
      if (hasAllMarkers) {
        return "unchanged";
      }
    }

    const appendBlock = buildIntegrationAppendBlock(spec);
    const placeAtTop = spec.relativePath === ".github/copilot-instructions.md" || spec.relativePath.endsWith(".mdc");
    const next = isMarkdown
      ? upsertMarkdownIntegrationBlock(existing, appendBlock, placeAtTop)
      : `${existing.trimEnd()}\n\n${appendBlock}`;

    if (next.trim() === existing.trim()) {
      return "unchanged";
    }

    await fs.writeFile(filePath, next, "utf8");
    return "updated";
  } catch (error) {
    const errorCode = (error as NodeJS.ErrnoException).code;
    if (errorCode !== "ENOENT") {
      throw error;
    }

    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, spec.content, "utf8");
    return "created";
  }
}

async function writeIfMissing(filePath: string, content: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return false;
  } catch {
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, content, "utf8");
    return true;
  }
}

const GIT_HOOK_STUB = `#!/bin/sh
# awesome-context-engine pre-commit hook
# Refreshes AI context on every commit. Zero background RAM usage.
# To activate: cp .awesome-context/hooks/pre-commit .git/hooks/pre-commit
#              chmod +x .git/hooks/pre-commit
npx awesome-context-engine context:refresh --quiet
`;

export async function initProject(rootDir: string): Promise<InitResult> {
  const contextPaths = getContextPaths(rootDir);
  const created: string[] = [];
  const skipped: string[] = [];

  await fs.mkdir(contextPaths.contextDir, { recursive: true });
  await fs.mkdir(contextPaths.skillsDir, { recursive: true });
  await fs.mkdir(contextPaths.memoryDir, { recursive: true });
  await fs.mkdir(path.join(contextPaths.contextDir, "experiences"), { recursive: true });
  await fs.mkdir(path.join(contextPaths.skillsDir, "drafts"), { recursive: true });
  const hooksDir = path.join(contextPaths.contextDir, "hooks");
  await fs.mkdir(hooksDir, { recursive: true });
  await writeIfMissing(path.join(hooksDir, "pre-commit"), GIT_HOOK_STUB);

  const memoryStoreFiles: Array<{ filePath: string; content: string }> = [
    { filePath: contextPaths.memoryItemsPath, content: "[]\n" },
    { filePath: contextPaths.memorySummariesPath, content: "[]\n" },
    { filePath: contextPaths.memoryIndexPath, content: '{\n  "byTag": {},\n  "byType": {},\n  "updatedAt": null\n}\n' }
  ];

  for (const entry of memoryStoreFiles) {
    const wasCreated = await writeIfMissing(entry.filePath, entry.content);
    const relativePath = path.relative(rootDir, entry.filePath) || entry.filePath;
    if (wasCreated) {
      created.push(relativePath);
    } else {
      skipped.push(relativePath);
    }
  }

  for (const entry of CONTEXT_FILES) {
    const filePath = entry.path(contextPaths);
    const wasCreated = await writeIfMissing(filePath, entry.content);
    const relativePath = path.relative(rootDir, filePath) || filePath;
    if (wasCreated) {
      created.push(relativePath);
    } else {
      skipped.push(relativePath);
    }
  }

  for (const entry of INTEGRATION_FILES) {
    const filePath = path.join(rootDir, entry.relativePath);
    const status = await ensureIntegrationFile(filePath, entry);
    if (status === "created" || status === "updated") {
      created.push(entry.relativePath);
    } else {
      skipped.push(entry.relativePath);
    }
  }

  return { created, skipped };
}
